/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-07-05 22:10:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>Administrator Login</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<!--link rel=\"stylesheet/less\" href=\"less/bootstrap.less\" type=\"text/css\" /-->\r\n");
      out.write("\t<!--link rel=\"stylesheet/less\" href=\"less/responsive.less\" type=\"text/css\" /-->\r\n");
      out.write("\t<!--script src=\"js/less-1.3.3.min.js\"></script-->\r\n");
      out.write("\t<!--append ÃÂ¢ÃÂÃÂ#!watchÃÂ¢ÃÂÃÂ to the browser URL, then refresh the page. -->\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/smoke.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/addProductStyle.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n");
      out.write("  <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"js/html5shiv.js\"></script>\r\n");
      out.write("  <![endif]-->\r\n");
      out.write("\r\n");
      out.write("  <!-- Fav and touch icons -->\r\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"img/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"img/apple-touch-icon-114-precomposed.png\">\r\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"img/apple-touch-icon-72-precomposed.png\">\r\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\" href=\"img/apple-touch-icon-57-precomposed.png\">\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"img/favicon.png\">\r\n");
      out.write("  \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/smoke.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/addProductScripts.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/callback.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/loginCheckScript.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"user_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row clearfix\">\r\n");
      out.write("\t\t<div class=\"col-md-12 column\">\r\n");
      out.write("\t\t\t<h2 class=\"text-info\">\r\n");
      out.write("\t\t\tBlack Magic Woman - PRODAVNICA NAMESTAJA\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<h4 class=\"text-info\"> Rad sa namestajem - dodavanje namestaja</h4>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<form id=\"back_form\" action=\"ProductStartServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"user_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<button id=\"rad_saloni\" class=\"btn btn-default\" type=\"submit\" form=\"back_form\">\r\n");
      out.write("\t\t\t\t\t\t\t Povratak\r\n");
      out.write("\t\t\t</button> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br>\t\t\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<form  id=\"coki\" role=\"form\" method=\"post\" action=\"ProductStartServlet\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- CODE input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Sifra namestaja</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t  <input id=\"code\" name=\"code\" placeholder=\"Unesite sifru namestaja\" class=\"form-control input-md\" smk-type=\"number\" minlength=\"3\" maxlength=\"9\"  type=\"text\" required>  \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- NAZIV input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Naziv namestaja</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t  <input id=\"name\" name=\"name\" placeholder=\"Unesite naziv namestaja\" class=\"form-control input-md\" type=\"text\" required>  \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- BOJA input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Naziv boje</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t         <select id=\"color\" name=\"color\" class=\"form-control\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Izaberite boju</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"crna\">crna</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"plava\">plava</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"crna\">crna</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"braon\">braon</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"siva\">siva</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"zelena\">zelena</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"narandzasta\">narandzasta</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ruzicasta\">ruzicasta</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"purpurna\">purpurna</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"crvena\">crvena</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bela\">bela</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"zuta\">zuta</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- BOJA input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Zemlja porekla</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t         <select id=\"origin\" name=\"origin\" class=\"form-control\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Izaberite</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Afghanistan\">Afghanistan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Ãland Islands\">Ãland Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Albania\">Albania</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Algeria\">Algeria</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"American Samoa\">American Samoa</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Andorra\">Andorra</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Angola\">Angola</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Anguilla\">Anguilla</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Antarctica\">Antarctica</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Antigua and Barbuda\">Antigua and Barbuda</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Argentina\">Argentina</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Armenia\">Armenia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Aruba\">Aruba</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Australia\">Australia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Austria\">Austria</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Azerbaijan\">Azerbaijan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bahamas\">Bahamas</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bahrain\">Bahrain</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bangladesh\">Bangladesh</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Barbados\">Barbados</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Belarus\">Belarus</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Belgium\">Belgium</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Belize\">Belize</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Benin\">Benin</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bermuda\">Bermuda</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bhutan\">Bhutan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bolivia\">Bolivia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bosnia and Herzegovina\">Bosnia and Herzegovina</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Botswana\">Botswana</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bouvet Island\">Bouvet Island</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Brazil\">Brazil</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"British Indian Ocean Territory\">British Indian Ocean Territory</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Brunei Darussalam\">Brunei Darussalam</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bulgaria\">Bulgaria</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Burkina Faso\">Burkina Faso</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Burundi\">Burundi</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Cambodia\">Cambodia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Cameroon\">Cameroon</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Canada\">Canada</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Cape Verde\">Cape Verde</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Cayman Islands\">Cayman Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Central African Republic\">Central African Republic</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Chad\">Chad</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Chile\">Chile</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"China\">China</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Christmas Island\">Christmas Island</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Cocos (Keeling) Islands\">Cocos (Keeling) Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Colombia\">Colombia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Comoros\">Comoros</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Congo\">Congo</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Congo, The Democratic Republic of The\">Congo, The Democratic Republic of The</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Cook Islands\">Cook Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Costa Rica\">Costa Rica</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Cote D'ivoire\">Cote D'ivoire</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Croatia\">Croatia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Cuba\">Cuba</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Cyprus\">Cyprus</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Czech Republic\">Czech Republic</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Denmark\">Denmark</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Djibouti\">Djibouti</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Dominica\">Dominica</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Dominican Republic\">Dominican Republic</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Ecuador\">Ecuador</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Egypt\">Egypt</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"El Salvador\">El Salvador</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Equatorial Guinea\">Equatorial Guinea</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Eritrea\">Eritrea</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Estonia\">Estonia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Ethiopia\">Ethiopia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Falkland Islands (Malvinas)\">Falkland Islands (Malvinas)</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Faroe Islands\">Faroe Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Fiji\">Fiji</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Finland\">Finland</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"France\">France</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"French Guiana\">French Guiana</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"French Polynesia\">French Polynesia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"French Southern Territories\">French Southern Territories</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Gabon\">Gabon</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Gambia\">Gambia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Georgia\">Georgia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Germany\">Germany</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Ghana\">Ghana</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Gibraltar\">Gibraltar</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Greece\">Greece</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Greenland\">Greenland</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Grenada\">Grenada</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Guadeloupe\">Guadeloupe</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Guam\">Guam</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Guatemala\">Guatemala</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Guernsey\">Guernsey</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Guinea\">Guinea</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Guinea-bissau\">Guinea-bissau</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Guyana\">Guyana</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Haiti\">Haiti</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Heard Island and Mcdonald Islands\">Heard Island and Mcdonald Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Holy See (Vatican City State)\">Holy See (Vatican City State)</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Honduras\">Honduras</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Hong Kong\">Hong Kong</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Hungary\">Hungary</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Iceland\">Iceland</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"India\">India</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Indonesia\">Indonesia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Iran, Islamic Republic of\">Iran, Islamic Republic of</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Iraq\">Iraq</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Ireland\">Ireland</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Isle of Man\">Isle of Man</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Israel\">Israel</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Italy\">Italy</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Jamaica\">Jamaica</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Japan\">Japan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Jersey\">Jersey</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Jordan\">Jordan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Kazakhstan\">Kazakhstan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Kenya\">Kenya</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Kiribati\">Kiribati</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Korea, Democratic People's Republic of\">Korea, Democratic People's Republic of</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Korea, Republic of\">Korea, Republic of</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Kuwait\">Kuwait</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Kyrgyzstan\">Kyrgyzstan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Lao People's Democratic Republic\">Lao People's Democratic Republic</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Latvia\">Latvia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Lebanon\">Lebanon</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Lesotho\">Lesotho</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Liberia\">Liberia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Libyan Arab Jamahiriya\">Libyan Arab Jamahiriya</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Liechtenstein\">Liechtenstein</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Lithuania\">Lithuania</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Luxembourg\">Luxembourg</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Macao\">Macao</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Macedonia, The Former Yugoslav Republic of\">Macedonia, The Former Yugoslav Republic of</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Madagascar\">Madagascar</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Malawi\">Malawi</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Malaysia\">Malaysia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Maldives\">Maldives</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mali\">Mali</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Malta\">Malta</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Marshall Islands\">Marshall Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Martinique\">Martinique</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mauritania\">Mauritania</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mauritius\">Mauritius</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mayotte\">Mayotte</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mexico\">Mexico</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Micronesia, Federated States of\">Micronesia, Federated States of</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Moldova, Republic of\">Moldova, Republic of</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Monaco\">Monaco</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mongolia\">Mongolia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Montenegro\">Montenegro</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Montserrat\">Montserrat</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Morocco\">Morocco</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mozambique\">Mozambique</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Myanmar\">Myanmar</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Namibia\">Namibia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Nauru\">Nauru</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Nepal\">Nepal</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Netherlands\">Netherlands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Netherlands Antilles\">Netherlands Antilles</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"New Caledonia\">New Caledonia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"New Zealand\">New Zealand</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Nicaragua\">Nicaragua</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Niger\">Niger</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Nigeria\">Nigeria</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Niue\">Niue</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Norfolk Island\">Norfolk Island</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Northern Mariana Islands\">Northern Mariana Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Norway\">Norway</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Oman\">Oman</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Pakistan\">Pakistan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Palau\">Palau</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Palestinian Territory, Occupied\">Palestinian Territory, Occupied</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Panama\">Panama</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Papua New Guinea\">Papua New Guinea</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Paraguay\">Paraguay</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Peru\">Peru</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Philippines\">Philippines</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Pitcairn\">Pitcairn</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Poland\">Poland</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Portugal\">Portugal</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Puerto Rico\">Puerto Rico</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Qatar\">Qatar</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Reunion\">Reunion</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Romania\">Romania</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Russian Federation\">Russian Federation</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Rwanda\">Rwanda</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Saint Helena\">Saint Helena</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Saint Kitts and Nevis\">Saint Kitts and Nevis</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Saint Lucia\">Saint Lucia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Saint Pierre and Miquelon\">Saint Pierre and Miquelon</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Saint Vincent and The Grenadines\">Saint Vincent and The Grenadines</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Samoa\">Samoa</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"San Marino\">San Marino</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Sao Tome and Principe\">Sao Tome and Principe</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Saudi Arabia\">Saudi Arabia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Senegal\">Senegal</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Serbia\">Serbia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Seychelles\">Seychelles</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Sierra Leone\">Sierra Leone</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Singapore\">Singapore</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Slovakia\">Slovakia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Slovenia\">Slovenia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Solomon Islands\">Solomon Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Somalia\">Somalia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"South Africa\">South Africa</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"South Georgia and The South Sandwich Islands\">South Georgia and The South Sandwich Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Spain\">Spain</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Sri Lanka\">Sri Lanka</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Sudan\">Sudan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Suriname\">Suriname</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Svalbard and Jan Mayen\">Svalbard and Jan Mayen</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Swaziland\">Swaziland</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Sweden\">Sweden</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Switzerland\">Switzerland</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Syrian Arab Republic\">Syrian Arab Republic</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Taiwan, Province of China\">Taiwan, Province of China</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Tajikistan\">Tajikistan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Tanzania, United Republic of\">Tanzania, United Republic of</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Thailand\">Thailand</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Timor-leste\">Timor-leste</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Togo\">Togo</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Tokelau\">Tokelau</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Tonga\">Tonga</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Trinidad and Tobago\">Trinidad and Tobago</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Tunisia\">Tunisia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Turkey\">Turkey</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Turkmenistan\">Turkmenistan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Turks and Caicos Islands\">Turks and Caicos Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Tuvalu\">Tuvalu</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Uganda\">Uganda</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Ukraine\">Ukraine</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"United Arab Emirates\">United Arab Emirates</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"United Kingdom\">United Kingdom</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"United States\">United States</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"United States Minor Outlying Islands\">United States Minor Outlying Islands</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Uruguay\">Uruguay</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Uzbekistan\">Uzbekistan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Vanuatu\">Vanuatu</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Venezuela\">Venezuela</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Viet Nam\">Viet Nam</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Virgin Islands, British\">Virgin Islands, British</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Virgin Islands, U.S.\">Virgin Islands, U.S.</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Wallis and Futuna\">Wallis and Futuna</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Western Sahara\">Western Sahara</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Yemen\">Yemen</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Zambia\">Zambia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Zimbabwe\">Zimbabwe</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- PROIZVODJAC input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Naziv proizvodjaca</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t  <input id=\"producer\" name=\"producer\" placeholder=\"Unesite naziv proizvodjaca\" class=\"form-control input-md\" type=\"text\" required>  \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- PRICE input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Cena proizvoda</label>  \r\n");
      out.write("\t\t\t\t  <input id=\"price\" name=\"price\" placeholder=\"Unesite cenu proizvoda(u dinarima)\" smk-type=\"number\" minlength=\"2\" maxlength=\"15\" class=\"form-control input-md\" type=\"text\" required>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- KOLICINA input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Kolicina proizvoda na lageru</label>  \r\n");
      out.write("\t\t\t\t  <input id=\"quantity\" name=\"quantity\" placeholder=\"quantity\" smk-type=\"number\" minlength=\"1\" maxlength=\"15\" class=\"form-control input-md\" type=\"text\" required>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- KATEGORIJA input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Izaberi kategoriju namestaja</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t         <select id=\"category\" name=\"category\" class=\"form-control\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Izaberite kategoriju</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- SALON input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Izaberi salon namestaja</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t         <select id=\"salon\" name=\"salon\" class=\"form-control\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Izaberite kategoriju</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- YEAR input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Godina proizvodnje namestaja</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t  <input id=\"productionYear\" name=\"productionYear\" placeholder=\"Unesite godinu proivodnje namestaja\" class=\"form-control input-md\" smk-type=\"number\" minlength=\"3\" maxlength=\"4\"  type=\"text\" required>  \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- AKCIJA input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Da li je na akciji?</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t         <select id=\"action\" name=\"action\" class=\"form-control\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Izaberite:</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"da\">da</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ne\">ne</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- STARTDATE input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\" id=\"start\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Datum pocetka akcije</label>  \r\n");
      out.write("\t\t\t\t  <div class=\"hero-unit\">\r\n");
      out.write("\t\t\t\t  <input id=\"startDate\" name=\"startDate\" placeholder=\"Kliknite za izbor datuma\"  type=\"text\">  \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- ENDDATE input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\" id=\"end\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Datum kraja akcije</label>  \r\n");
      out.write("\t\t\t\t  <div class=\"hero-unit\">\r\n");
      out.write("\t\t\t\t  <input id=\"endDate\" name=\"endDate\" placeholder=\"Kliknite za izbor datuma\"  type=\"text\">  \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- AKCIJA input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\" id=\"akcija\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Procenat popusta?</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t         <select id=\"percent\" name=\"percent\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Izaberite:</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10%</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20\">20%</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"30\">30%</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"40\">40%</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"50\">50%</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"60\">60%</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"70\">70%</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"80\">80%</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"90\">90%</option>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- SALON input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Izaberi besplatnu uslugu</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t         <select id=\"freeService\" name=\"freeService\" class=\"form-control\" required>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Izaberite kategoriju</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"ne\">Bez besplatne usluge</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- PROIZVODJAC input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Link do videa</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t  <input id=\"video\" name=\"video\" placeholder=\"Unesite link videa sa youtube-a\" class=\"form-control input-md\" type=\"text\">  \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- PROIZVODJAC input-->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  <label  for=\"textinput\">Link do slike</label>  \r\n");
      out.write("\t\t\t\t  <div>\r\n");
      out.write("\t\t\t\t  <input id=\"picture\" name=\"picture\" placeholder=\"Unesite link ili putanju do slike\" class=\"form-control input-md\" type=\"text\">  \r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"user_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t <button  name=\"salonButton\"  id=\"dugme\" type=\"submit\" class=\"btn btn-default\">Unesi salon</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /addProduct.jsp(398,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/addProduct.jsp(398,7) '${category}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${category}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /addProduct.jsp(398,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("k");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${k.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${k.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /addProduct.jsp(415,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/addProduct.jsp(415,7) '${salons}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${salons}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /addProduct.jsp(415,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("s");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /addProduct.jsp(497,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/addProduct.jsp(497,7) '${services}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${services}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /addProduct.jsp(497,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("ser");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ser.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ser.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }
}
